### ISSUE TITLE
sqlite3 error

### ISSUE THREAD

**Issue by DuckyGit** [Kaluub/forumbot#1]
i keep getting errors about sqlite3

**Comment by DuckyGit** [comment]
Fixed the issue bot i can't open GuildSettings.sqlite because it doesn't exist

**Comment by Kaluub** [comment]
Hello:
Thanks for showing interest in this project. As for your issue, you need to add a new folder that isn't in the GitHub for security reasons.
From README.md:
Add a folder named "private", and inside it you will need 2 files. Inside, you will make another folder named "models", which will store the databases, and you will also need a file called "config.json".

In your "config.json" file, simply copy:

{
    "token":"your-bot-token-here"
}
Replace "your-bot-token-here" with the token found under the bot section at https://discord.com/developers/applications.

I forgot to mention in that file that you need to create a folder called "models" in the /private/ directory as well. Can add that right now.

Also, for future reference, I don't plan on supporting this repository much anymore. Currently more interested in my project "petbot" and another private project anymore. Apologies for the late response!

**Comment by DuckyGit** [comment]
Thanks, Just didn't read the readme all the way. I love the bot you made! <3
